### ISSUE TITLE
NPM package not in sync with icons listed on website

### ISSUE THREAD

**Issue by Senne** [resolvetosavelives/healthicons#218]
Some icons appear to be missing in the latest NPM package `healthicons@1.0.2`. For instance, Symbols > Body Mass Index is [listed on the website](https://healthicons.org/icon/outline/symbols/body_mass_index) but it isn't included in the package.

**Comment by nburka** [comment]
Thanks for bringing that to my attention @Senne . We have to update our processes to make sure we update NPM each time we release new icons. I've just released `1.0.3` which should include all of the latest icons. Let me know if that works for you.

**Comment by Senne** [comment]
That works, thanks for the update!

**Comment by jvolker** [comment]
It seems this is still an issue, unfortunately. https://healthicons.org/icon/filled/devices/ecmo is not part of the latest NPM package 2.0.0.

**Comment by jvolker** [comment]
> It seems this is still an issue, unfortunately. https://healthicons.org/icon/filled/devices/ecmo is not part of the latest NPM package 2.0.0.

@dburka and @nburka did you see my comment here? This is still an issue and should be reopened, maybe.
